//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class ChooseCollor : global::System.Configuration.ApplicationSettingsBase {
        
        private static ChooseCollor defaultInstance = ((ChooseCollor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ChooseCollor())));
        
        public static ChooseCollor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsWhite {
            get {
                return ((bool)(this["IsWhite"]));
            }
            set {
                this["IsWhite"] = value;
            }
        }
    }
}
